name: sunray
description: "The Better Jellyfin Client (Not Associated with The Jellyfin Team)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.18
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Shrikhand
      fonts:
        - asset: assets/fonts/shrikhand.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 20
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#ffffff"
    theme_color: "#DD9037"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 250
  macos:
    generate: true
    image_path: "assets/images/icon.png"