name: sunray
description: "The Better Jellyfin Client (Not Associated with The Jellyfin Team)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.18
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Shrikhand
      fonts:
        - asset: assets/fonts/shrikhand.ttf
