name: Build iOS unsigned

on:
  workflow_dispatch: # Manual trigger from GitHub UI

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Flutter
      uses: flutter-actions/setup-flutter@v4.0

    - name: Install Flutter dependencies
      run: flutter pub get

    - name: Build iOS (no codesign)
      run: flutter build ios --release --no-codesign

    - name: Package .app into .ipa
      run: |
        mkdir -p Payload
        cp -r build/ios/iphoneos/Runner.app Payload/
        zip -r Runner.ipa Payload

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: Runner-unsigned
        path: Runner.ipa
